version: 0.0
os: linux
hooks:
  BeforeInstall:
  - location: cd_setenvironment.sh
    runas: ubuntu
  AfterInstall:
  - location: cd_startapp.sh
    runas: ubuntu
  ValidateService:
  - location: cd_stopapp.sh
    runas: ubuntu